@startuml
'https://plantuml.com/class-diagram
'
'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList

class Video {
Long videoId
String title
int length
int viewCount
String description
Date videoPosted
@oneToMany
column commentId
List<Tags>
getVideoId()
setVideoId()
getTitle()
setTitle()
getViewCount()
incrementViewCount()
getDescription()
setDescription()
getDatePosted()
setDatePosted()
selectVideo()
startVideo()
pauseVideo()
stopVideo()
postVideo()
autoPlayVideo()
addTag()
}

class Display {
String settings
String volume
fullScreen()
theaterModeScreen()
changeVolume()
}

User <-- Admin
User <-- BasicUser

Abstract class User{
Long userId;
String email;
String userName;
String password;
String firstName;
String lastName;
getUserId()
setUserId()
getEmail()
setEmail()
getUserName()
setUserName
getPassword()
setPassword()
getFirstName()
setFirstName()
getLastName()
setLastName()
commentOnVideo()
likeVideo()
dislikeVideo()
@oneToMany
column commentId
}

class Admin{
List<Video> postedVideos;
showAllVideos()
deleteVideo()
banUser()
}

class BasicUser {
List<Video> likedVideos;
List<Video> postedVideos;
showUserVideos()
deleteVideo()
uploadVideo()
}

class Comment {
Long commentId;
String text
Date datePosted
@ManyToOne
column videoId
@ManyToOne
column userId
getCommentId()
setCommentId()
submitComment()
getCommentDate()
setCommentDate()
likeComment()
dislikeComment()
}

class Tags {
Object[] elementData

}



enum VideoStatus {
PUBLIC
PRIVATE
UNLISTED
}

@enduml