

cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: us-east-1
      stack:
        auto: false

application:
  bucket:
    name: ziptube1


server:
  port: 5000


